### ISSUE TITLE
Any plans for highlighting?

### ISSUE THREAD

**Issue by AceofSpades5757** [polarmutex/tree-sitter-beancount#12]
I'm still new to the tree-sitter arena, but I was wondering if there were any plans on adding any of the "queries" items, particularly highlighting.

Thanks!

**Comment by polarmutex** [comment]
The highlighting queries are in the nvim-treesitter repo, I can add here if needed

**Comment by AceofSpades5757** [comment]
That would be great, I think. I wanted to add beancount support to the Helix editor, which appears to pull the tree-sitter repository down to build and use. I'm still figuring out how tree-sitter is consumed, so I'm not sure, although that appears what Helix wants.

**Comment by AceofSpades5757** [comment]
Or maybe not. I'll look into it later.

**Comment by AceofSpades5757** [comment]
Going from Helix, your Neovim repository, and a message I got, it looks like these files are generally provided in the editor, plugin, etc. so I'll take what was provided in the Helix PR and add it there. Thank you for your time and consideration.
