### ISSUE TITLE
Editing balance assertion line freezes entire Neovim

### ISSUE THREAD

**Issue by wzyboy** [polarmutex/tree-sitter-beancount#19]
Minimal reproducible example:

```
; vim: ft=beancount:

2023-06-25 balance Assets:SomeBank 123.00 CAD

**** example example example

2022-06-24 * "example"
  Income:SomeCompany
  Assets:SomeBank
```

Steps to reproduce:

1. Move cursor to the position before `123.00 CAD`
2. Type `C` to change the amount
3. Neovim freezes with high CPU usage

Note that the `**** example` line is required to reproduce the issue. Without the line everything works as expected.

Neovim version:

```
$ nvim --version
NVIM v0.9.1
```

Both `neovim-treesitter` and `tree-sitter-beancount` plugins have been updated to latest commits.

**Comment by polarmutex** [comment]
I was able to reproduce it, I will take a look into it and see if I can fix the issue

**Comment by polarmutex** [comment]
I do not see problem on master branch anymore after my PR. 

might take a few days  for nvim-treesitter to pick up commit and update the lockfile

re open  if you still seeing problems
