### ISSUE TITLE
Build error because of reference to not existing file src/scanner.cc

### ISSUE THREAD

**Issue by jamilraichouni** [polarmutex/tree-sitter-beancount#39]
Hi!

When I run `:Lazy update` I get an error:

<img width="1552" alt="Screenshot 2024-02-29 at 23 04 42" src="https://github.com/polarmutex/tree-sitter-beancount/assets/45113557/55350965-4b9e-49cb-adbc-39e88ca8df27">

Note that this is very similar to https://github.com/nickel-lang/tree-sitter-nickel/issues/40

Also of interest is that there is no error when I command `:TSInstall beancount` afterwards (in Neovim).

**Comment by polarmutex** [comment]
is this still an issue?

**Comment by jamilraichouni** [comment]
No, seems to be solved.
